spring:
  datasource:
    name: topic-talk # Name of the data source
    type: com.zaxxer.hikari.HikariDataSource # Type of data source
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver # JDBC driver class name
      # Automatically commit connections returned from the pool
      auto-commit: true
      # Minimum number of idle connections maintained in the pool
      minimum-idle: 5
      # Database connection timeout, default is 30 seconds, which is 30000
      idle-timeout: 60000
    url: jdbc:mysql://localhost:3306/topic-talks-app?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root # Database username
    password: p4ssw0rd! # Database password

  jpa:
    show-sql: true # Show SQL statements
    properties:
      hibernate:
        format_sql: true # Format SQL statements

## Socket Io Configuration
socket-server:
  # Socket Port
  port: 8085
  # Socket Host
  host: 127.0.0.1
  # Number of connections
  workCount: 100
  #Allow client requests
  allowCustomRequests: true
  # Protocol upgrade timeout (milliseconds), default 10 seconds
  upgradeTimeout: 10000
  # Ping message timeout (milliseconds), default 60 seconds
  pingTimeout: 6000000
  # Ping message interval (milliseconds), default is 25 seconds.
  pingInterval: 2500000
  #Set the maximum content length of HTTP interaction
  maxHttpContentLength: 1048576
  #Set the maximum length of data processed per frame to prevent others from using big data to attack the server
  maxFramePayloadLength: 1048576