CREATE TRIGGER INSERT_AGE_USER_TRIGGER
    BEFORE UPDATE ON user
    FOR EACH ROW
BEGIN
    IF NEW.dob IS NULL THEN
        SET NEW.age = 0;
    ELSE
        SET NEW.age = TIMESTAMPDIFF(YEAR, NEW.dob, CURDATE());
END IF;
END;